version: '3.10'
services:
  web:
      build: .
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - static_data:/eshop/static
      ports:
           - 8000:8000
      restart: "always"
      env_file:
        - ./.env
      depends_on:
        - db

  db:
    image: postgres:14-alpine
    restart: "always"
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOSTNAME}
      - POSTGRES_PORT=${DB_PORT}
      - PGHOST=/System/Volumes/Data/private/tmp/.s.PGSQL.5432

volumes:
  static_data:
  postgres_data:

